services:
  - type: web
    name: ytv-streaming-app
    env: static
    buildCommand: npm run build
    staticPublishPath: ./webos-app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
